name: CI moseiik
on:
    push:
        branches:
            - main
            - b-HAMID
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                platform: [linux/amd64, linux/arm64]
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU (ARM64 only)
              if: matrix.platform == 'linux/arm64'
              uses: docker/setup-qemu-action@v4
              with:
                 platforms: linux/arm64

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Build Docker image
              run: |
                docker build --platform ${{ matrix.platform }} -t moseiik-test --load .
            - name: Run tests
              run : |
                docker run --rm --platform ${{ matrix.platform }} moseiik-test
              